
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd wordpress-app
      - npm install -g aws-cdk
      - npm install

  pre_build:
    commands:
      - npm run test

  build:
    commands:
      - npm run build
      - cdk synth

  post_build:
    commands:
      - cdk deploy --require-approval never
      - echo "Deployment completed successfully!"